language: python

python:
  - "2.7"
before_install:
  - sudo apt-get install -y libevent-dev

install: "pip install -r requirements_dev.txt --use-mirrors"

script: nosetests iati_datastore
cache: true
