language: python

python:
  - "2.7"
before_install:
  - sudo apt-get install -y libevent-dev

install:
  - "pip install -r requirements_dev.txt --use-mirrors"
  - "pip install coverage"
before_script: mkdir -p shippable/testresults shippable/codecoverage
script: 
  - nosetests iati_datastore --with-coverage --cover-package=iati-datastore  --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage xml -o shippable/codecoverage/coverage.xml 
cache: true
